apiVersion: v1
kind: Service
metadata:
  name: cocktail-manager-db
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cocktail-manager-db
spec:
  serviceName: "cocktail-manager-db" # reference to the service created above.
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/bitnami/postgresql:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cocktail-manager-db
              key: postgres-password
        ports:
        - containerPort: 5432
          name: postgresql