apiVersion: v1
data:
  postgres-password: a0BUIWdWV0ZkZWFvRjlHYmFnNjI=
  postgres-user: cG9zdGdyZXM=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: cocktail-manager-db
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-07-02T07:36:48Z"
  labels:
    app.kubernetes.io/instance: cocktail-manager-db
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.6.0
  name: cocktail-manager-db-postgresql
  namespace: default
  resourceVersion: "2842556"
  uid: 0817de73-4f68-49e7-86ef-c017eb2c5893
type: Opaque
