name: Deploy CocktailManager
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.2
      - name: Install dependencies
        run: npm install
      - name: Build and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r -o StrictHostKeyChecking=no ./* $USER@$HOST:/home/ubuntu/CocktailManager
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'ENDSSH'
            cd /home/ubuntu/CocktailManager/cocktail-manager-auth/api
            docker-compose up -d --build
          ENDSSH
