name: Deploy CocktailManager
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          path: ./cocktail-manager-auth
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and run Docker containers
        run: |
          cd cocktail-manager-auth/api
          docker-compose up -d --build
